function saveCheckerboardNoiseForAnalysis(seed, mu, sigma, checksX, checksY, stimFrames, updateEveryNFrames, savePath)
% saveCheckerboardNoiseForAnalysis
%
% Exports the exact checkerboard noise sequence generated by the MATLAB
% stimulus scripts to a .mat file, ensuring perfect cross-language
% reproducibility with the Python analysis suite (CheckerboardSTA.py).
%
% Usage:
%   saveCheckerboardNoiseForAnalysis(2)
%   saveCheckerboardNoiseForAnalysis(2, 0.5, 0.3, 40, 32, 600, 1)
%
% The output .mat file can be loaded by CheckerboardSTA.py to bypass
% any potential seed/RNG differences between MATLAB and NumPy.

    if nargin < 1, seed = 2; end
    if nargin < 2, mu = 0.5; end
    if nargin < 3, sigma = 0.3; end
    if nargin < 4, checksX = 40; end
    if nargin < 5, checksY = 32; end
    if nargin < 6, stimFrames = 600; end
    if nargin < 7, updateEveryNFrames = 1; end
    if nargin < 8, savePath = ''; end

    nUpdates = ceil(stimFrames / updateEveryNFrames);

    % Generate noise using the exact same RandStream as the stimulus scripts
    stream = RandStream('mt19937ar', 'Seed', seed);
    noiseVals = mu + sigma .* randn(stream, checksY, checksX, nUpdates);
    noiseVals = min(max(noiseVals, 0), 1);  % clamp to [0, 1]

    % Build output path
    if isempty(savePath)
        savePath = fullfile(pwd, 'data', sprintf('checkerboard_noise_seed%d.mat', seed));
    end

    % Ensure output directory exists
    [outDir, ~, ~] = fileparts(savePath);
    if ~exist(outDir, 'dir')
        mkdir(outDir);
    end

    % Save the noise sequence and metadata
    save(savePath, 'noiseVals', 'seed', 'mu', 'sigma', ...
         'checksX', 'checksY', 'stimFrames', 'updateEveryNFrames', 'nUpdates');

    fprintf('Checkerboard noise sequence saved to:\n  %s\n', savePath);
    fprintf('  Shape: %d x %d x %d (rows x cols x updates)\n', checksY, checksX, nUpdates);
end
