function saveCheckerboardNoiseForAnalysis(seed, mu, sigma, checksX, checksY, stimFrames, updateEveryNFrames, colorMode, savePath)
% saveCheckerboardNoiseForAnalysis
%
% Exports the exact checkerboard noise sequence generated by the MATLAB
% stimulus scripts to BOTH a .mat file and a .csv file, ensuring perfect
% cross-language reproducibility with the Python analysis suite.
%
% The .mat file contains the raw noise values (checksY x checksX x nUpdates).
% The .csv file contains one row per FRAME with brightness values (0-255)
% for every checkerboard square, fully expanded (including held frames).
%
% CSV columns: frame, time_s, r1_c1, r1_c2, ..., r{checksY}_c{checksX}
%
% Usage:
%   saveCheckerboardNoiseForAnalysis(2)
%   saveCheckerboardNoiseForAnalysis(2, 0.5, 0.3, 40, 32, 600, 1, 'greyscale')

    if nargin < 1, seed = 2; end
    if nargin < 2, mu = 0.5; end
    if nargin < 3, sigma = 0.3; end
    if nargin < 4, checksX = 40; end
    if nargin < 5, checksY = 32; end
    if nargin < 6, stimFrames = 600; end
    if nargin < 7, updateEveryNFrames = 1; end
    if nargin < 8 || isempty(colorMode), colorMode = 'greyscale'; end
    if nargin < 9, savePath = ''; end

    preFrames  = 5;
    postFrames = 5;
    totalFrames = preFrames + stimFrames + postFrames;
    refreshRate = 60;
    nUpdates = ceil(stimFrames / updateEveryNFrames);

    % Generate noise using the exact same RandStream as the stimulus scripts
    stream = RandStream('mt19937ar', 'Seed', seed);
    noiseVals = mu + sigma .* randn(stream, checksY, checksX, nUpdates);
    noiseVals = min(max(noiseVals, 0), 1);  % clamp to [0, 1]

    % ---- Save .mat (unchanged from original) ----
    if isempty(savePath)
        matPath = fullfile(pwd, 'data', sprintf('checkerboard_noise_seed%d.mat', seed));
    else
        matPath = savePath;
    end

    [outDir, ~, ~] = fileparts(matPath);
    if ~exist(outDir, 'dir'), mkdir(outDir); end

    save(matPath, 'noiseVals', 'seed', 'mu', 'sigma', ...
         'checksX', 'checksY', 'stimFrames', 'updateEveryNFrames', 'nUpdates');

    fprintf('Checkerboard noise (.mat) saved to:\n  %s\n', matPath);
    fprintf('  Shape: %d x %d x %d (rows x cols x updates)\n', checksY, checksX, nUpdates);

    % ---- Save .csv (per-frame brightness, all squares) ----
    csvPath = fullfile(outDir, sprintf('checkerboard_noise_%s_seed%d.csv', colorMode, seed));

    fid = fopen(csvPath, 'w');

    % Header: frame, time_s, r1_c1, r1_c2, ..., rY_cX
    fprintf(fid, 'frame,time_s');
    for row = 1:checksY
        for col = 1:checksX
            fprintf(fid, ',r%d_c%d', row, col);
        end
    end
    fprintf(fid, '\n');

    % Data: one row per frame
    for f = 1:totalFrames
        time_s = (f - 1) / refreshRate;
        fprintf(fid, '%d,%.6f', f, time_s);

        if f <= preFrames || f > (preFrames + stimFrames)
            % Pre/post: all zeros
            for sq = 1:(checksY * checksX)
                fprintf(fid, ',0');
            end
        else
            stimF = f - preFrames;
            updateIdx = min(max(floor((stimF - 1) / updateEveryNFrames) + 1, 1), nUpdates);
            v = noiseVals(:, :, updateIdx);  % checksY x checksX

            % Write brightness values row-by-row, column-by-column
            for row = 1:checksY
                for col = 1:checksX
                    val = round(v(row, col) * 255);
                    fprintf(fid, ',%d', val);
                end
            end
        end
        fprintf(fid, '\n');
    end

    fclose(fid);

    fprintf('Checkerboard noise (.csv) saved to:\n  %s\n', csvPath);
    fprintf('  %d frames x %d squares, %s mode\n', totalFrames, checksY * checksX, colorMode);
end
